services:
  db:
    image: postgres:17-alpine
    container_name: orbit-space-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: orbit_user
      POSTGRES_PASSWORD: orbit_password
      POSTGRES_DB: orbit_db
    ports:
      - '5432:5432'
    volumes:
      - 'F:/Docker-vault/Orbit-space/PosgreSql:/var/lib/postgresql/data'

networks:
  default:
    name: orbit-space-network
